# Generated by Django 3.1.2 on 2020-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Baby and Child health', 'Baby and Child health'), ('Treatments and Medicaments', 'Treatments and Medicaments'), ('Treatments and Medicaments', 'Treatments and Medicaments'), ('First Aid', 'First Aid'), ('Sexual Wellbeing', 'Sexual Wellbeing'), ('Personal Care', 'Personal Care')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
